/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/scene.gltf -t -o components/TVModel.tsx 
Author: assetfactory (https://sketchfab.com/assetfactory)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/generic-television-set-bda5bb7328e64e688f5359d51e15e656
Title: Generic Television set
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cylinder001_ConectorMetal_0: THREE.Mesh
    Cube012_PatternWhite_0: THREE.Mesh
    Cube007_Metal_0: THREE.Mesh
    Cube006_MetalRough_0: THREE.Mesh
    Cube005_Screen_0: THREE.Mesh
    Cube003_Metal_0: THREE.Mesh
    Cube003_ConectorNegroPlastic_0: THREE.Mesh
  }
  materials: {
    ConectorMetal: THREE.MeshStandardMaterial
    PatternWhite: THREE.MeshStandardMaterial
    Metal: THREE.MeshStandardMaterial
    MetalRough: THREE.MeshStandardMaterial
    Screen: THREE.MeshStandardMaterial
    ConectorNegroPlastic: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/scene.gltf') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0, -170.738, 79.083]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Cube003_Metal_0.geometry} material={materials.Metal} />
        <mesh geometry={nodes.Cube003_ConectorNegroPlastic_0.geometry} material={materials.ConectorNegroPlastic} />
      </group>
      <mesh geometry={nodes.Cylinder001_ConectorMetal_0.geometry} material={materials.ConectorMetal} position={[118.208, -86.48, -9.268]} scale={100} />
      <mesh geometry={nodes.Cube012_PatternWhite_0.geometry} material={materials.PatternWhite} position={[0, -39.314, -10.702]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.Cube007_Metal_0.geometry} material={materials.Metal} position={[0, -32.818, -9.261]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.Cube006_MetalRough_0.geometry} material={materials.MetalRough} position={[0, -157.509, 0.225]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.Cube005_Screen_0.geometry} material={materials.Screen} position={[0, -39.314, 0.064]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
    </group>
  )
}

useGLTF.preload('/scene.gltf')
